branches:
  only:
  - main
language: python
python:
- '3.8'
- '3.9'
install:
- pip install .
script:
- python3 -m unittest discover
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: sJCsD8pu2qI6hSCJp7dowPsvFj1JvV+sdPJcEJjw2IrcT9ePWX8gz2b20cZhlrLtkssNZjbLdn4jJOzrnsqkdj6vymCIT4gYC2JB5JcRGSyz3D6z61Xp9qodBtP6TfLtHuNy26lbvxh0eDCAa4NY3MkeycO1oIGykpnbw99i3QKT0Sfsh03luQhLdmuGXpGHCPwPDhRz91m1IZtxQCKz1a4t0n3KJmXFqNpuPej6ECHJlev8Kxc5ORCxeTwDIriDBnDu3ujRnkfHWwa1s3zIBAt1gQEjulpCrVJ/mT5WstcijuRxoTs9k61hYLk7EVlK84T4DzWQdwch7ceVx/i038afvZOgqA3v8E0eXjE2ulMw9VIT8rCrpnZDGfafB6R2L+Kc28/gGFMVSm8aQBIXhsWcb6JQrrG2V2gQ7oRVed9DnKHm8VDBnmN/yuGxw9Jo22F/PvaH5BsKX8FM7tLN/mHiLuYFnHUZBMMETg2W9zeXtoP7rINWRLOhtak87R74wclVLApVx392YMpZIQ9cUr34wUNtYdeDYHGnDqEAoCutGKeyGi9RRNGNdwIwyE8jCKv6bL1XHTxJUxrnGyl6Ydn4VofX+nXE8uCV/PYwGB1A/kww/GH9RFDm02n32zAd1jHjI3PNn50WJALGHwwecjnHy6aJowsLWSHvnp61G88=
